package ru.descend.bot.lolapi.dto

import com.google.gson.annotations.SerializedName
import ru.descend.bot.lolapi.LeagueMainObject.LOL_VERSION

data class ChampionsDTO(
    val type: String,
    val format: String,
    val version: String,
    val data: Data,
)

data class Data(
    @SerializedName("Aatrox") val aatrox: InterfaceChampionBase,
    @SerializedName("Ahri") val ahri: InterfaceChampionBase,
    @SerializedName("Akali") val akali: InterfaceChampionBase,
    @SerializedName("Akshan") val akshan: InterfaceChampionBase,
    @SerializedName("Alistar") val alistar: InterfaceChampionBase,
    @SerializedName("Amumu") val amumu: InterfaceChampionBase,
    @SerializedName("Anivia") val anivia: InterfaceChampionBase,
    @SerializedName("Annie") val annie: InterfaceChampionBase,
    @SerializedName("Aphelios") val aphelios: InterfaceChampionBase,
    @SerializedName("Ashe") val ashe: InterfaceChampionBase,
    @SerializedName("AurelionSol") val aurelionSol: InterfaceChampionBase,
    @SerializedName("Azir") val azir: InterfaceChampionBase,
    @SerializedName("Bard") val bard: InterfaceChampionBase,
    @SerializedName("Belveth") val belveth: InterfaceChampionBase,
    @SerializedName("Blitzcrank") val blitzcrank: InterfaceChampionBase,
    @SerializedName("Brand") val brand: InterfaceChampionBase,
    @SerializedName("Braum") val braum: InterfaceChampionBase,
    @SerializedName("Briar") val briar: InterfaceChampionBase,
    @SerializedName("Caitlyn") val caitlyn: InterfaceChampionBase,
    @SerializedName("Camille") val camille: InterfaceChampionBase,
    @SerializedName("Cassiopeia") val cassiopeia: InterfaceChampionBase,
    @SerializedName("Chogath") val chogath: InterfaceChampionBase,
    @SerializedName("Corki") val corki: InterfaceChampionBase,
    @SerializedName("Darius") val darius: InterfaceChampionBase,
    @SerializedName("Diana") val diana: InterfaceChampionBase,
    @SerializedName("Draven") val draven: InterfaceChampionBase,
    @SerializedName("DrMundo") val drMundo: InterfaceChampionBase,
    @SerializedName("Ekko") val ekko: InterfaceChampionBase,
    @SerializedName("Elise") val elise: InterfaceChampionBase,
    @SerializedName("Evelynn") val evelynn: InterfaceChampionBase,
    @SerializedName("Ezreal") val ezreal: InterfaceChampionBase,
    @SerializedName("Fiddlesticks") val fiddlesticks: InterfaceChampionBase,
    @SerializedName("Fiora") val fiora: InterfaceChampionBase,
    @SerializedName("Fizz") val fizz: InterfaceChampionBase,
    @SerializedName("Galio") val galio: InterfaceChampionBase,
    @SerializedName("Gangplank") val gangplank: InterfaceChampionBase,
    @SerializedName("Garen") val garen: InterfaceChampionBase,
    @SerializedName("Gnar") val gnar: InterfaceChampionBase,
    @SerializedName("Gragas") val gragas: InterfaceChampionBase,
    @SerializedName("Graves") val graves: InterfaceChampionBase,
    @SerializedName("Gwen") val gwen: InterfaceChampionBase,
    @SerializedName("Hecarim") val hecarim: InterfaceChampionBase,
    @SerializedName("Heimerdinger") val heimerdinger: InterfaceChampionBase,
    @SerializedName("Hwei") val hwei: InterfaceChampionBase,
    @SerializedName("Illaoi") val illaoi: InterfaceChampionBase,
    @SerializedName("Irelia") val irelia: InterfaceChampionBase,
    @SerializedName("Ivern") val ivern: InterfaceChampionBase,
    @SerializedName("Janna") val janna: InterfaceChampionBase,
    @SerializedName("JarvanIV") val jarvanIv: InterfaceChampionBase,
    @SerializedName("Jax") val jax: InterfaceChampionBase,
    @SerializedName("Jayce") val jayce: InterfaceChampionBase,
    @SerializedName("Jhin") val jhin: InterfaceChampionBase,
    @SerializedName("Jinx") val jinx: InterfaceChampionBase,
    @SerializedName("Kaisa") val kaisa: InterfaceChampionBase,
    @SerializedName("Kalista") val kalista: InterfaceChampionBase,
    @SerializedName("Karma") val karma: InterfaceChampionBase,
    @SerializedName("Karthus") val karthus: InterfaceChampionBase,
    @SerializedName("Kassadin") val kassadin: InterfaceChampionBase,
    @SerializedName("Katarina") val katarina: InterfaceChampionBase,
    @SerializedName("Kayle") val kayle: InterfaceChampionBase,
    @SerializedName("Kayn") val kayn: InterfaceChampionBase,
    @SerializedName("Kennen") val kennen: InterfaceChampionBase,
    @SerializedName("Khazix") val khazix: InterfaceChampionBase,
    @SerializedName("Kindred") val kindred: InterfaceChampionBase,
    @SerializedName("Kled") val kled: InterfaceChampionBase,
    @SerializedName("KogMaw") val kogMaw: InterfaceChampionBase,
    @SerializedName("KSante") val ksante: InterfaceChampionBase,
    @SerializedName("Leblanc") val leblanc: InterfaceChampionBase,
    @SerializedName("LeeSin") val leeSin: InterfaceChampionBase,
    @SerializedName("Leona") val leona: InterfaceChampionBase,
    @SerializedName("Lillia") val lillia: InterfaceChampionBase,
    @SerializedName("Lissandra") val lissandra: InterfaceChampionBase,
    @SerializedName("Lucian") val lucian: InterfaceChampionBase,
    @SerializedName("Lulu") val lulu: InterfaceChampionBase,
    @SerializedName("Lux") val lux: InterfaceChampionBase,
    @SerializedName("Malphite") val malphite: InterfaceChampionBase,
    @SerializedName("Malzahar") val malzahar: InterfaceChampionBase,
    @SerializedName("Maokai") val maokai: InterfaceChampionBase,
    @SerializedName("MasterYi") val masterYi: InterfaceChampionBase,
    @SerializedName("Milio") val milio: InterfaceChampionBase,
    @SerializedName("MissFortune") val missFortune: InterfaceChampionBase,
    @SerializedName("MonkeyKing") val monkeyKing: InterfaceChampionBase,
    @SerializedName("Mordekaiser") val mordekaiser: InterfaceChampionBase,
    @SerializedName("Morgana") val morgana: InterfaceChampionBase,
    @SerializedName("Naafiri") val naafiri: InterfaceChampionBase,
    @SerializedName("Nami") val nami: InterfaceChampionBase,
    @SerializedName("Nasus") val nasus: InterfaceChampionBase,
    @SerializedName("Nautilus") val nautilus: InterfaceChampionBase,
    @SerializedName("Neeko") val neeko: InterfaceChampionBase,
    @SerializedName("Nidalee") val nidalee: InterfaceChampionBase,
    @SerializedName("Nilah") val nilah: InterfaceChampionBase,
    @SerializedName("Nocturne") val nocturne: InterfaceChampionBase,
    @SerializedName("Nunu") val nunu: InterfaceChampionBase,
    @SerializedName("Olaf") val olaf: InterfaceChampionBase,
    @SerializedName("Orianna") val orianna: InterfaceChampionBase,
    @SerializedName("Ornn") val ornn: InterfaceChampionBase,
    @SerializedName("Pantheon") val pantheon: InterfaceChampionBase,
    @SerializedName("Poppy") val poppy: InterfaceChampionBase,
    @SerializedName("Pyke") val pyke: InterfaceChampionBase,
    @SerializedName("Qiyana") val qiyana: InterfaceChampionBase,
    @SerializedName("Quinn") val quinn: InterfaceChampionBase,
    @SerializedName("Rakan") val rakan: InterfaceChampionBase,
    @SerializedName("Rammus") val rammus: InterfaceChampionBase,
    @SerializedName("RekSai") val rekSai: InterfaceChampionBase,
    @SerializedName("Rell") val rell: InterfaceChampionBase,
    @SerializedName("Renata") val renata: InterfaceChampionBase,
    @SerializedName("Renekton") val renekton: InterfaceChampionBase,
    @SerializedName("Rengar") val rengar: InterfaceChampionBase,
    @SerializedName("Riven") val riven: InterfaceChampionBase,
    @SerializedName("Rumble") val rumble: InterfaceChampionBase,
    @SerializedName("Ryze") val ryze: InterfaceChampionBase,
    @SerializedName("Samira") val samira: InterfaceChampionBase,
    @SerializedName("Sejuani") val sejuani: InterfaceChampionBase,
    @SerializedName("Senna") val senna: InterfaceChampionBase,
    @SerializedName("Seraphine") val seraphine: InterfaceChampionBase,
    @SerializedName("Sett") val sett: InterfaceChampionBase,
    @SerializedName("Shaco") val shaco: InterfaceChampionBase,
    @SerializedName("Shen") val shen: InterfaceChampionBase,
    @SerializedName("Shyvana") val shyvana: InterfaceChampionBase,
    @SerializedName("Singed") val singed: InterfaceChampionBase,
    @SerializedName("Sion") val sion: InterfaceChampionBase,
    @SerializedName("Sivir") val sivir: InterfaceChampionBase,
    @SerializedName("Skarner") val skarner: InterfaceChampionBase,
    @SerializedName("Smolder") val smolder: InterfaceChampionBase,
    @SerializedName("Sona") val sona: InterfaceChampionBase,
    @SerializedName("Soraka") val soraka: InterfaceChampionBase,
    @SerializedName("Swain") val swain: InterfaceChampionBase,
    @SerializedName("Sylas") val sylas: InterfaceChampionBase,
    @SerializedName("Syndra") val syndra: InterfaceChampionBase,
    @SerializedName("TahmKench") val tahmKench: InterfaceChampionBase,
    @SerializedName("Taliyah") val taliyah: InterfaceChampionBase,
    @SerializedName("Talon") val talon: InterfaceChampionBase,
    @SerializedName("Taric") val taric: InterfaceChampionBase,
    @SerializedName("Teemo") val teemo: InterfaceChampionBase,
    @SerializedName("Thresh") val thresh: InterfaceChampionBase,
    @SerializedName("Tristana") val tristana: InterfaceChampionBase,
    @SerializedName("Trundle") val trundle: InterfaceChampionBase,
    @SerializedName("Tryndamere") val tryndamere: InterfaceChampionBase,
    @SerializedName("TwistedFate") val twistedFate: InterfaceChampionBase,
    @SerializedName("Twitch") val twitch: InterfaceChampionBase,
    @SerializedName("Udyr") val udyr: InterfaceChampionBase,
    @SerializedName("Urgot") val urgot: InterfaceChampionBase,
    @SerializedName("Varus") val varus: InterfaceChampionBase,
    @SerializedName("Vayne") val vayne: InterfaceChampionBase,
    @SerializedName("Veigar") val veigar: InterfaceChampionBase,
    @SerializedName("Velkoz") val velkoz: InterfaceChampionBase,
    @SerializedName("Vex") val vex: InterfaceChampionBase,
    @SerializedName("Vi") val vi: InterfaceChampionBase,
    @SerializedName("Viego") val viego: InterfaceChampionBase,
    @SerializedName("Viktor") val viktor: InterfaceChampionBase,
    @SerializedName("Vladimir") val vladimir: InterfaceChampionBase,
    @SerializedName("Volibear") val volibear: InterfaceChampionBase,
    @SerializedName("Warwick") val warwick: InterfaceChampionBase,
    @SerializedName("Xayah") val xayah: InterfaceChampionBase,
    @SerializedName("Xerath") val xerath: InterfaceChampionBase,
    @SerializedName("XinZhao") val xinZhao: InterfaceChampionBase,
    @SerializedName("Yasuo") val yasuo: InterfaceChampionBase,
    @SerializedName("Yone") val yone: InterfaceChampionBase,
    @SerializedName("Yorick") val yorick: InterfaceChampionBase,
    @SerializedName("Yuumi") val yuumi: InterfaceChampionBase,
    @SerializedName("Zac") val zac: InterfaceChampionBase,
    @SerializedName("Zed") val zed: InterfaceChampionBase,
    @SerializedName("Zeri") val zeri: InterfaceChampionBase,
    @SerializedName("Ziggs") val ziggs: InterfaceChampionBase,
    @SerializedName("Zilean") val zilean: InterfaceChampionBase,
    @SerializedName("Zoe") val zoe: InterfaceChampionBase,
    @SerializedName("Zyra") val zyra: InterfaceChampionBase,
)

open class InterfaceChampionBase (
    val id: String = "",
    val key: String = "",
    val name: String = "",
    val tags: List<String> = listOf()
) {
    fun getIconURL() : String {
        return "https://ddragon.leagueoflegends.com/cdn/$LOL_VERSION/img/champion/$id.png"
    }

    override fun toString(): String {
        return "InterfaceChampionBase(id='$id', key='$key', name='$name', tags=$tags)"
    }
}